#!/bin/zsh

if [[ -z $ZSHCOM_DSH_USEZSH ]]; then ZSHCOM_DSH_USEZSH=''; fi

function dockerShell() {
	if [[ $ZSHCOM_DSH_USEZSH == *${1}* ]]; then
		dockerZsh "$1"
	else
		docker exec -it "$1" bash
	fi
}

function dockerPorts() {
  docker container ls --format 'json' | \
    jq --slurp \
      'def trimWS: gsub("^\\s+";"") | gsub("\\s+$";""); def remPref: gsub("^:+";"") | gsub("^0.0.0.0:";""); def filterPorts: select( ( . | contains("->") ) ); def safeToNum: if test("^\\d+$") then tonumber else . end; def mapPorts:      map( (match("^([\\d-]+)->([\\d-]+)(/(tcp))?$") // null) as $m |      if $m then     {       host: $m.captures[0].string | safeToNum,       container: $m.captures[1].string | safeToNum,       protocol: ($m.captures[3].string // "both")     } else . end); def arrToDic:       sort_by(.names|ascii_downcase) |        map({     (.names|tostring): .ports     }) | add;  map({    names: .Names,    ports: (       (.Ports | split(",")) |         map( . | trimWS | filterPorts | remPref ) | unique | mapPorts    )  } | select( (.ports | length) > 0 ) )  | arrToDic'
}

function dockerPortsHost() {
  dockerPorts | jq 'to_entries | map(.value) | flatten | map(.host) | unique | sort[]'
}

perfwatch() {
	# shellcheck disable=SC2016
	sensors | ack -i '^(CPU|MB) Temp:\s+([\+\-\d.]+°[CF])' --output '$1:\t$2'
	echo ''
	echo ''
	# shellcheck disable=SC2016
	(cat /proc/cpuinfo | ack "^([c]pu MHz|processor)\s+:\s(.+)$" --output '$2') | ack '(\d+) (\d)(\d+)\.\d+ (\d+) (\d)(\d+)\.\d+ ' --output '$1\t$2.$3  $5.$6\t$4'
}

function shellColors() {
  isnum='^[0-9]+$'
  if [[ "$1" =~ $isnum && -n $2 ]] ; then
    echo '\\u001b[38;5;'$1'm'$2'\\033[0m';
    echo   "\u001b[38;5;$1m$2\033[0m";
  else
    echo '\n\n\\u001b[38;5;***COLOR CODE HERE***m ***TEXT*** \\033[0m  \n\n'
    for i in {0..255};
    do
      # shellcheck disable=SC2296
      # shellcheck disable=SC2298
      print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'};
    done

    echo ''
    echo ''
    echo 'zsh-toolkit tokens'
    echo ''

    for zc in $(printenv | grep -P 'zc[A-Z][a-z]+=' | grep -Po 'zc[A-Z][a-z]+'); do
      # shellcheck disable=SC2086
      eval echo -e "\$$zc" $zc "\$zcOFF";
    done
  fi
}

dockerZsh() {
	docker exec -it "$1" /bin/zsh
}

function pip_install_save {
  prefreeze=$(pip freeze);
  pip install "$1";
  res=$?;

  if [[ $res != 0 ]]; then
    return $res;
  fi

  postfreeze=$(pip freeze);

  if [[ "$prefreeze" == "$postfreeze" ]]; then
    return 0;
  fi

  line=$(pip freeze | ack "^$1=");

  if [[ -n "$line" ]]; then
    if [[ "$line" =~ "\n" ]]; then
      echo "Multiple matches on $1 in freeze"
      echo "$line"
    else
      echo "$line" >> ./requirements.txt
    fi
  else
    echo "$1 not found in freeze"
  fi
}

function set_title() {
  echo -e "\033]0;$1\007";
}

if [[ -n $ZSHCOM__known_os && $ZSHCOM__known_os == 'win' ]]
then
  function psack () {
    # shellcheck disable=SC2086
    ps aux -W | ack -v '/ack ' | ack -i $1
  }
else
  function psack () {
    # shellcheck disable=SC2086
    ps aux | ack -v '/ack ' | ack -i $1
  }
fi

function listExt() {
  find "${1:-.}"/**/* -type f | ack '[^.]+$' -o | sort | uniq
}

function findWithExtension() {
  badImg='\.(jpg_.+|r\d+|me-downloaders|torrent)$'

  if [[ $1 == '-bimg' ]]
  then
    #echo "find ./ -type f | ack -i \"${badImg}\""
    find ./ -type f | ack -i "${badImg}"
    return
  fi

  if [[ $1 == '-empty' ]]
   then
     find ./ -type f | ack -i "/[^./]+$"
     return
   fi

  rx='\.('

  # shellcheck disable=SC2068
  for a in $@
  do
    if [[ $rx != '\.(' ]]
    then
      rx="${rx}|"
    fi
    rx="${rx}${a}"
  done

  rx="${rx})$"
  #echo "find ./ -type f | ack \"${rx}\""
  find ./ -type f | ack -i "${rx}"
}

function touchFiles() {
  rec=''
  root=$1

  if [[ "$*" == *"-r"* ]]
  then
      rec='-r'
  fi

  if [[ ! -d $root ]]
  then
    echo invalid path
    return
  fi

  if [[ $rec == '-r' ]]
  then
#    echo recurse
    find "$root" -type f -exec touch {} +
  else
#    echo top
    find "$root" -maxdepth 1  -type f -exec touch {} +
  fi
}

function rclsa() {
  rclone lsd --max-depth 1 "$@";
  echo '---'
  rclone lsl --max-depth 1 "$@";
}


