#!/bin/zsh

if [[ ${ZSHCOM__feat_rclone:?} == true ]]
then
  alias rmv="rclone move -P --ignore-existing"
else
  _trace "rclone not installed"
fi

alias listDirs="find ./ -type d"

function dirItemCount() {
  echo $((($(ls -Al "$1" | wc -l)-1)));
}

function whatsmyip() {
  if commandExists curl && commandExists jq; then
    curl -sS https://ipinfo.io/json | jq '.'
  elif commandExists host; then
    # shellcheck disable=SC2016
    host myip.opendns.com resolver1.opendns.com | ack 'myip.opendns.com has address ([\d.]+)' --output '\$1'
  elif commandExists curl; then
    curl checkip.amazonaws.com
  else
    >&2 echo "host nor curl commands available"
    exit 1
  fi
}

if [[ $ZSHCOM__known_os == 'win' ]]; then  alias clip="tee /dev/clipboard";
else
  if [[ "$TERM" == 'xterm-kitty' ]] && commandExists kitten; then
    alias clip="tee >(kitten clipboard)";
  elif commandExists xclip; then
    alias clip="tee >(xclip -r -selection clipboard)";
  elif commandExists wl-copy; then
    alias clip="tee >(wl-copy -n)";
  fi
fi

if commandExists qrencode; then
  alias qrencode='qrencode -t UTF8'
fi

# shellcheck disable=SC2154
alias popout='upd=$(dirname "$(pwd)"); while [[ ! -d "$upd" ]]; do upd=$(dirname "$upd"); done; cd "$upd"'

### System
# shellcheck disable=SC2142
# shellcheck disable=SC2154
alias ztk-varCache="for f in \$(find \$ZSHCOM/.var*); do echo \$(basename \$f) | ack '^\.var_(.+)$' --output '\$1'; cat \$f; done"

# shellcheck disable=SC2142
alias dockerStop='$HOME/scripts/dockerStop.sh $@'
alias rmrf='rm -rf'

if commandExists bat; then
  alias view='bat -pp';
else
  alias view='nano -Sv';
fi

if ! command -v json_pp &> /dev/null
then
  alias json_pp='python3 -m json.tool'
fi

if ! command -v xml_pp &> /dev/null
then
  if command -v xmllint &> /dev/null
  then
    alias xml_pp="xmllint --format -"
  else
    echo No xml pretty printer
  fi
fi

alias lsa='ls -lha --group-directories-first';
alias sulsa='sudo ls -lha --group-directories-first'

function ssh_alias() {
  name=$1
  host=$2

  if [[ -n $4 ]]; then
    user=$3
    ident=$4
  elif [[ -n $3 ]]; then
    if [[ -f $3 ]]; then
      ident=$3
      user=$(whoami)
    else
      ident="$HOME/.ssh/id_ed25519"
      user=$3
    fi
  else
    ident="$HOME/.ssh/id_ed25519"
    user=$(whoami)
  fi

  if [[ "$TERM" == "xterm-kitty" ]]
  then
    alias "$name"="kitty +kitten ssh ${user}@${host} -i $ident"
  else
    alias "$name"="ssh ${user}@${host} -i $ident"
  fi
}

function catskip() {
  N=$(( $1 + 1 ));
  tail -n "+$N" $2;
}

function jtail() {
  # shellcheck disable=SC2068
  tail -qF $@ | jq -C .
}

if commandExists perl; then
  # shellcheck disable=SC2154
  alias unique="perl -ne 'print unless \$seen{\$_}++'"
fi
