#!/bin/zsh

if [[ ${ZSHCOM__feat_rclone:?} == true ]]
then
  alias rmv="rclone move -P --ignore-existing"
else
  _trace "rclone not installed"
fi

alias listDirs="find ./ -type d"
# shellcheck disable=SC2142
alias whatsmyip="host myip.opendns.com resolver1.opendns.com | ack 'myip.opendns.com has address ([\d.]+)' --output '\$1'"
alias whatsmyip-curl="curl checkip.amazonaws.com"

if [[ -n $ZSHCOM__known_os && $ZSHCOM__known_os == 'win' ]]; then  alias clip="tee /dev/clipboard";
else alias clip="tee >(xclip -r -selection clipboard)"; fi

# shellcheck disable=SC2154
alias popout='upd=$(dirname "$(pwd)"); while [[ ! -d "$upd" ]]; do upd=$(dirname "$upd"); done; cd "$upd"'

### System
# shellcheck disable=SC2142
# shellcheck disable=SC2154
alias ztk-varCache="for f in \$(find \$ZSHCOM/.var*); do echo \$(basename \$f) | ack '^\.var_(.+)$' --output '\$1'; cat \$f; done"

# shellcheck disable=SC2142
alias dockerStop='$HOME/scripts/dockerStop.sh $@'
alias rmrf='rm -rf'
alias view='nano -Sv'

if ! command -v json_pp &> /dev/null
then
  alias json_pp='python3 -m json.tool'
fi

if ! command -v xml_pp &> /dev/null
then
  if command -v xmllint &> /dev/null
  then
    alias xml_pp="xmllint --format -"
  else
    echo No xml pretty printer
  fi
fi
