export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

# cd $ZSH_CUSTOM/plugins
plugins=(
	git
	autoupdate					#https://github.com/TamCore/autoupdate-oh-my-zsh-plugins
	zsh-autosuggestions			#https://github.com/zsh-users/zsh-autosuggestions
	zsh-syntax-highlighting		#https://github.com/zsh-users/zsh-syntax-highlighting.git
)

source $ZSH/oh-my-zsh.sh

ZSHCOM="$HOME/.zsh-toolkit"

source $ZSHCOM/init.sh

