export ZSH="$HOME/.oh-my-zsh"

# shellcheck disable=SC2034
ZSH_THEME="robbyrussell"

# shellcheck disable=SC2034
plugins=(
	git
	autoupdate					#https://github.com/TamCore/autoupdate-oh-my-zsh-plugins
	zsh-autosuggestions			#https://github.com/zsh-users/zsh-autosuggestions
	zsh-syntax-highlighting		#https://github.com/zsh-users/zsh-syntax-highlighting.git
)

# shellcheck disable=SC2086
source $ZSH/oh-my-zsh.sh

export PATH="$PATH:$HOME/.local/bin"
ZSHCOM="$HOME/.zsh-toolkit"
source "$ZSHCOM"/init.sh

